### ISSUE TITLE
Support type: kubernetes.io/tls 

### ISSUE THREAD

**Issue by derrickburns** [godaddy/kubernetes-external-secrets#109]

**Comment by Flydiverny** [comment]
Does this require anything more than being able to set type in the external secret resource?

Example:
```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-dockerhub-secret
secretDescriptor:
  backendType: secretsManager
  type: kubernetes.io/dockerconfigjson
  data:
    - key: /development/mma/dockerhub
      name: .dockerconfigjson
```

Where the value in backend would be 
```json
{"auths":{"https://index.docker.io/v1/":{"auth":"bXljcmVkZW50aWFsczp2ZXJ5LW5pY2UtcGFzc3dvcmQ="}}}
```

Similarly could be done for tls?

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-tls
secretDescriptor:
  backendType: secretsManager
  type: kubernetes.io/tls
  data:
    - key: /development/mma/certifcate
      property: crt
      name: tls.crt
    - key: /development/mma/certifcate
      property: key
      name: tls.key
```
