### ISSUE TITLE
Unable to Fetch SSM Parameter

### ISSUE THREAD

**Issue by rsajjan3** [godaddy/kubernetes-external-secrets#120]
Hi, I'm attempting to use External Secrets to fetch a parameter(SecureString) stored in Systems Manager, but I am met with this error message

> {"level":50,"time":1563397164220,"pid":16,"hostname":"external-secrets-766d65c4d9-frzb4","type":"Error","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined\n    at Function.from (buffer.js:207:11)\n    at externalData.forEach (/app/lib/backends/kv-backend.js:72:43)\n    at Array.forEach (<anonymous>)\n    at SystemManagerBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:71:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","msg":"The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined","v":1}

My secrets YAML is defined as
```apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test-token
  namesapce: default
secretDescriptor:
  backendType: systemManager
  data:
    - key: /path/to/test
      name: test
```
Fetching secrets from SecretsManager works as expected, but when attempting to fetch Parameters from SSM I am met with the error above.

**Comment by dbirks** [comment]
I'm just started using this project today, but I had to troubleshoot some while getting it set up.
Looks like `namespace` is misspelled, but that's a copy-paste error maybe?

I have been successful with just using  
```
  data:
    - key: /path/to/test
```
and leaving `name` off.

**Comment by dbirks** [comment]
And actually my `- key` is indented differently on my working object:
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: widgetuploader-password
  namespace: default
secretDescriptor:
  backendType: systemManager
  data:
  - key: /widgetuploader/dev/password
```
