### ISSUE TITLE
Support for IAM Roles for self managed cluster with Kiam

### ISSUE THREAD

**Issue by sreedharbukya** [godaddy/kubernetes-external-secrets#142]
Hey Team, 

I am working with IAM Roles to access the services of AWS.  I am building a self-managed cluster on AWS with help of kops tool. All my app deployments uses IAM roles to access AWS Services using [Kiam](https://github.com/uswitch/kiam) service. 

I have added AWS Role in deployment configuration as follows. 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kubernetes-external-secrets
  name: kubernetes-external-secrets
  namespace: kubernetes-external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubernetes-external-secrets
  template:
    metadata:
      labels:
        name: kubernetes-external-secrets
        service: kubernetes-external-secrets
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::12312312312:role/Development-Secrets-Manager-Role
    spec:
      serviceAccountName: kubernetes-external-secrets-service-account
      containers:
        - image: "godaddy/kubernetes-external-secrets:1.2.2"
          imagePullPolicy: Always
          name: kubernetes-external-secrets
          env:
            - name: AWS_REGION
              value: ap-southeast-1
```

It doesn't work. It is throws errors like unable to find the credentials. But, It works with if I provide AWS_ACCESS_KEY_ID & AWS_SECRET_KEYs as environment vars to deployment. 

Please can support or help if I am doing something wrong.
