### ISSUE TITLE
Support to have IAM user Assume a Role when retrieving secret data

### ISSUE THREAD

**Issue by GeoffMillerAZ** [godaddy/kubernetes-external-secrets#143]
External Secrets could better sever multi-account setups if it allows the IAM User specified to retrieve secrets not only based on an IAM User but also an IAM Role.

The following example goes so far as to allow you to specify a role for each value retrieval. Probably all retrievals within a single secret will generally come from the same AWS account but this suggestion allows for maximum flexibility in case you need a secret comprised of secrets stored from multiple accounts. The example of username/password would never be the case but I left it with the basic example. Even just having a roleArn filed that is used for the entire ExternalSecret would be just fine. The IAM user would just have to have permissions to assume these roles and you're good.
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-service
secretDescriptor:
  backendType: secretsManager
  data:
    - key: hello-service/credentials
      name: password
      property: password
      roleArn: arn:aws:iam::123456789012:role/somerole
    - key: hello-service/credentials
      name: username
      property: username
      roleArn: arn:aws:iam::210987654321:role/somerole
```

The default behavior, should `roleArn` not be present, should be to just use the IAM creds directly without assuming a role.

OR

```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-service
secretDescriptor:
  backendType: secretsManager
  roleArn: arn:aws:iam::123456789012:role/somerole
  data:
    - key: hello-service/credentials
      name: password
      property: password
    - key: hello-service/credentials
      name: username
      property: username
```

**Comment by GeoffMillerAZ** [comment]
you could even extend this concept into:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-service
secretDescriptor:
  data:
    - key: hello-service/credentials
      name: password
      property: password
      backendType: secretsManager
      roleArn: arn:aws:iam::123456789012:role/somerole
    - key: hello-service/credentials
      name: username
      property: username
      backendType: systemManager
      roleArn: arn:aws:iam::210987654321:role/somerole
```

This would allow you to mix and match backends to combine them into a single secret. The best and most flexible idea seems to have these keys at the top layer and on each secret. If specified at the top, that is what is used for each unless overridden downstream.

**Comment by moolen** [comment]
As an extension to your porposal i would like to suggest the following to restrict access to Roles per Namespace:

RN a k8s-client can create a `ExternalSecret` and use any role for any account. E.g. Assume this: We have Team A in namespace `team-a` and Team B in `team-b`. Now Team A could access the SSM/SM secrets of Team B. To fix this i would like to restrict the to-be-assumed-roles an a per-namespace basis.The following example is implemented by [kiam](https://github.com/uswitch/kiam):

```yaml
kind: Namespace
metadata:
  name: iam-example
  annotations:
    # this annotation restricts access to certain accounts/roles
    iam.amazonaws.com/permitted: arn:aws:iam::123456789012:*
```

This would allow `ExternalSecret`s in the namespace `iam-example` to only assume roles matching the regex `arn:aws:iam::123456789012:*`.

@GeoffMillerAZ  do you have input about this?

**Comment by GeoffMillerAZ** [comment]
I think you can just say that the IAM user/role that the external secrets controller will be using should be responsible for controlling which roles it can assume along with the trust relationship on the target IAM role. So you could put this role on the IAM user/role external secrets controller is using:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Resource": [
                "arn:aws:iam::123teamAAccount321:role/someRole",
                "arn:aws:iam::123teamCAccount321:role/someRole",
                "arn:aws:iam::123teamDAccount321:role/someOtherRole",
            ],
            "Effect": "Allow"
        }
    ]
}
```

This would then let it assume the roles-account combos listed so long as those roles trust the IAM account where this is defined. This should provide sufficient control and is required anyway.

But this does bring up a potential issue of maybe also benefiting from defining the IAM user/role that each external secret is going to use to assume the specified role. That way you can fully define the permissions needed on each external secret. You could also apply this on each actual data point that gets pulled in and just inherit from the main external secret body if not specified on each data pull.

```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-service
secretDescriptor:
  backendType: secretsManager
  backendConfig:
    authType: user
    userSecretRef: someSecretName
    roleArn:  arn:aws:iam::123456789012:role/somerole
  data:
    - key: hello-service/credentials
      name: password
      property: password
      backendType: secretsManager
      backendConfig:
        authType: role
        roleArn: arn:aws:iam::666666789012:role/somerole
    - key: hello-service/credentials
      name: username
      property: username
```

where `backendConfig` specifies what authType is to be used. `user` for iam user and `role` for the iam role if running on an EC2 with an instance profile or using KIAM.

An `authType` of `user` will expect to find a `userSecretRef` that is the name of a secret to tell it how to find the aws credentials with data keys `aws_access_key_id` and `aws_secret_access_key`. It will then log into this to pull the secrets. But if roleArn is specified in the `backendConfig` it will first assume that role before trying to read that secret.

An `authType` of `role` will expect use the iam role of the pod/node (depending on setup of the cluster) to pull the secret. If it sees a specified `roleArn` it will use the iam role of the pod/node to instead assume the specified `roleArn` and then read the secret.

A `backendConfig` with `authType` of `user` would support the following usage:
```
backendConfig:
        authType: <user> (required)
        userSecretRef: <name of secret to get aws access keys> (required)
        region: (optional and defaults to the default region of the aws config)
        roleArn: <valid iam role arn to assume> (optional)
```

A `backendConfig` with `authType` of `role` would support the following usage:
```
backendConfig:
        authType: <role> (required)
        region: (optional and defaults to the default region of the aws config)
        roleArn: <valid iam role arn to assume> (optional)
```

If backendConfig is not specified `authType: role` would be defaulted to. `backendConfig` can be specified at the `secretDescriptor` level or on an instance in the `data` level. The `backendConfig` at the `secretDescriptor` level should be used if an instance in the `data` level does not specify any config.

I know it's a bit of a change from my first suggestion but this would give the most amount of control on a per-secret basis. And I think whoever sets up these users and roles should be where the restrictions occur.
