### ISSUE TITLE
feat: support SecretBinary

### ISSUE THREAD

**Issue by TarekAS** [godaddy/kubernetes-external-secrets#149]
Sometimes, my secret is in binary format, and I have to base64 it to properly store it. This is one of the main reason k8s secrets are base64.

This is not currently possible with this controller. I suggest something like this:

```
secretDescriptor:
  backendType: secretsManager
  data:
    - key: my-secret
      name: secret1
      property: normal-secret
    - key: my-secret
      name: secret2
      property: binary-secret
      encode: false # Do not base64 the secret. Is set to 'true' by default.
```
