### ISSUE TITLE
Enforcing naming conventions for AWS Secrets Manager (and HashiCorp Vault) entries

### ISSUE THREAD

**Issue by muenchhausen** [godaddy/kubernetes-external-secrets#178]
_1. "As cluster operations, I want to force developers to follow namespace based naming conventions on AWS Secrets Manager, 
because secrets are just presented as a single list in the AWS console without any grouping possibilty. There is no other way than naming convention to tidy up and to prevent naming clashes."_

_2. "As an IT security manager, I want to enforce in a simple way, that Team A cannot access secrets of Team B, because AssumeRole is for some setups far too complicated."_

The proposed solution is an enforced naming convention defined as annotation within the namespaces in addition to #143.

**Given:**

As an example AWS Secrets Manager naming convention could look like folder names starting with
deployment stage, followed by a namespace and ending with a secret name:

```
 dev/team-a-namespace/order-service
 dev/team-b-namespace/delivery-service
```

```
kind: Namespace
metadata:
  name: team-a-namespace
  annotations:
    # this annotation checks naming convention for AWS Secrets Manager entries
    secretsmanager.amazonaws.com/naming: dev/team-a-namespace/.*

---
kind: Namespace
metadata:
  name: team-b-namespace
  annotations:
    # this annotation checks naming convention for AWS Secrets Manager entries
    secretsmanager.amazonaws.com/naming: dev/team-b-namespace/.*
```

```
# Team A - valid naming
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: team-a-namespace
  name: order-service
secretDescriptor:
  backendType: secretsManager
  data:
    # valid naming:
    - key: dev/team-a-namespace/order-service
      name: password
      property: password
      backendType: secretsManager

---
# Team A - invalid naming
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: team-a-namespace
  name: order-service
secretDescriptor:
  backendType: secretsManager
  data:
    # invalid naming:
    - key: order-service
      name: password
      property: password
      backendType: secretsManager

---
# Team B - no access
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  namespace: team-b-namespace
  name: order-service
secretDescriptor:
  backendType: secretsManager
  data:
    # invalid naming:
    - key: dev/team-a-namespace/order-service
      name: password
      property: password
      backendType: secretsManager

```

**When**
Checking naming convention in the poller module 

**Then**
Team A should be able to retrieve the first secret. Team B should be rejected, because
it does not follow the naming convention of the namespace.
      
**A possible implementation** 
... could be the following (file poller.js):

```
const annotationNamingKey = 'secretsmanager.amazonaws.com/naming'
...
_isPermitted (namespace, descriptor) {
  const role = descriptor.roleArn
  let allowed = true
  let reason = ''

  if (!namespace.metadata.annotations) {
    return {
      allowed, reason
    }
  }

  // an empty annotation value allows access to all roles
  const re = new RegExp(namespace.metadata.annotations[annotationPermittedKey])

  if (!re.test(role)) {
    allowed = false
    reason = `namespace does not allow to assume role ${role}`
  }

  # PATCH start
  const externalData = descriptor.data || descriptor.properties
  const namingConvention = namespace.metadata.annotations[annotationNamingKey]

  if (namingConvention) {
    externalData.forEach((secretProperty, index) => {    
      const reNaming = new RegExp(namingConvention)
      if (!reNaming.test(secretProperty.key)) {
        allowed = false
        reason = `secret key ${secretProperty.key} does not match naming convention ${namingConvention} of the namespace`
      }
    })
  }
  # PATCH end

  return {
    allowed,
    reason
  }
}
```

What is your opinion? If this proposal is fine, I will work on a pull request including some tests.
