### ISSUE TITLE
CRD status field

### ISSUE THREAD

**Issue by moolen** [godaddy/kubernetes-external-secrets#185]
/kind feature

As a creator of `ExternalSecret`s  i want to know the `status` of the sync process. Because we're relying on 3rd party APIs it can happen that they are **unavailable** or - due to misconfiguration - we **can not access** them.

Without actively looking into the logs or having proper alerts in place using the `sync_calls` metrics there is no way to tell if the secret is actually up to date.

Why are these options not enough? 

1. looking into logs might not be possible because a different team owns the service (think "platform" or "devops" :trollface: or whatever)

2. Most issues arise while bootstrapping (setting up roles, secrets etc.) and - from my experience - people just don't write alerts before they actually implement stuff.

To Σ this up: Having a `status` field is more than a nice-to-have feature. It actually would have solved a bunch of support requests.   
 

#### Proposal

The following would be a MVP implementation:
* the timestamp of the last sync action
* the error that might have occurred during that sync action  

risks:
* we could potentially expose sensitive information in these error messages. 

```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-world
secretDescriptor:
  backendType: secretsManager
  data: {}
  # add this field 
status:
  lastSync: 1572384571963 # unix timestamp
  lastSyncResult: "unable to assume role arn:aws:iam::123456789012:role/test-role"
  observedGeneration: 866
```

Relates to #178 

Please vote :+1: :-1: if you would find it helpful and/or comment if you have further suggestions
