### ISSUE TITLE
Feature: CRD `version` field for re-fetching secrets 

### ISSUE THREAD

**Issue by anarcher** [godaddy/kubernetes-external-secrets#201]
if ExternalSecret has `version` field, The controller fetches the data from SSM and changes `status.version`  if the `version` field is not equal to  `status.version`.   With it, We can trigger to re-fetching with various ways (like Job or deploy tools)

What do you think? :-)

```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test1
secretDescriptor:
  version: 2
  backendType: systemManager
  data:
    - key: /test/test1
      name: test-test1
status:
  version: 1
```

**Comment by Flydiverny** [comment]
Is this just to change something to force triggering a new poll? I think you could do this already now, if you change anything under `secretDescriptor` kubernetes should increase the generation of the resource, which will trigger a new poll since >2.0.0 tracks generation and sets observedGeneration in status

**Comment by anarcher** [comment]
Thank you, This works! 

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  generation: 4
  name: test1
secretDescriptor:
  backendType: systemManager
  data:
  - key: /test/test1
    name: test-test1
  version: 2 // If we change this field, the controller do sync :-D.
status:
  lastSync: "2019-11-07T18:19:11.166Z"
  observedGeneration: 4
  status: SUCCESS
```

Another idea is that if we can save ExternalSecret`s observedGeneration into  Secrets, we can check this synced or not during deployment. 

```
apiVersion: v1
data:
  test-test1: dGVzdA==
kind: Secret
metadata:
  creationTimestamp: "2019-11-07T16:22:13Z"
  name: test1
  namespace: user-ted-1
  annotations:
        observedGeneration: 4 // ExternalSecrets's  observedGeneration. or ownerReference.status. 
  ownerReferences:
  - apiVersion: kubernetes-client.io/v1
    controller: true
    kind: ExternalSecret
    name: test1
    uid: c097a293-017a-11ea-b5b7-025cc67b3366
type: Opaque
```

**Comment by Flydiverny** [comment]
If you want to manually set something and have it propagate you can use the new `template` field added in 2.1.0 :)

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: test1
secretDescriptor:
  backendType: systemManager
  template:
    metadata:
      annotations:
        version: 2 # <--
  data:
  - key: /test/test1
    name: test-test1
```

which should give you a secret like:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test1
  annotations:
    version: 2 # <--
data:
  test-test1: dGVzdA==
type: Opaque
```
