### ISSUE TITLE
Vault backend only supports K/V Version 2, add support for Version 1

### ISSUE THREAD

**Issue by jmreicha** [godaddy/kubernetes-external-secrets#248]
Attempting to get the Vault integration working, using the example from the Readme.

```
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test-external-secret
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: kubernetes-external-secrets
  data:
    - name: password
      key: kubernetes/test/test-external-secret
      property: password
```

Here's the error I get when I create the ExternalSecret.

```
The ExternalSecret "test-external-secret" is invalid:
* : Invalid value: "": "spec" must validate one and only one schema (oneOf). Found none valid
* spec.backendType: Unsupported value: "vault": supported values: "secretsManager", "systemManager"
```

Checked the Docker image and it is `kubernetes-external-secrets:2.2.1`, I am basically using the defaults from the Helm chart.   Maybe I'm just missing something?

**Comment by Flydiverny** [comment]
As a workaround please try this: 

```yaml
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test-external-secret
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: kubernetes-external-secrets
  key: "should-not-be-here"
  data:
    - name: password
      key: kubernetes/test/test-external-secret
      property: password
```

Try adding a `key` to the same level as `vault*` to see if that bypasses the validation. Looks like something got in which shouldn't be there https://github.com/godaddy/kubernetes-external-secrets/blob/b163a6908d1de0ca956acbbdbd38de798bbcf784/crd.yaml#L79-L86

**Comment by jmreicha** [comment]
Thanks, that seems to have fixed it.

**Comment by jmreicha** [comment]
I am now getting the following error, running low on ideas of how to debug it.

```
{"level":20,"time":1576638247441,"pid":17,"hostname":"kubernetes-external-secrets-688654fb5-hccxx","msg":"reading secret key kubernetes/dev/test-external-secret from vault","v":1}
{"level":50,"time":1576638247491,"pid":17,"hostname":"kubernetes-external-secrets-688654fb5-hccxx","response":{"statusCode":404,"body":{"request_id":"25c647e9-e041-5f64-f412-1e01b7d5b2a9","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv get' for this operation."],"auth":null}},"msg":"failure while polling the secret default/josh-external-secret","stack":"Error: Status 404\n    at handleVaultResponse (/app/node_modules/node-vault/src/index.js:49:21)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async VaultBackend._get (/app/lib/backends/vault-backend.js:54:28)\n    at async /app/lib/backends/kv-backend.js:29:31\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)\n    at async VaultBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:99:42)\n    at async Poller._createSecretManifest (/app/lib/poller.js:86:18)\n    at async Poller._upsertKubernetesSecret (/app/lib/poller.js:150:28)","type":"Error","v":1}
{"level":20,"time":1576638247495,"pid":17,"hostname":"kubernetes-external-secrets-688654fb5-hccxx","msg":"updating status for default/test-external-secret to: ERROR, Status 404","v":1}
```

I am able to grab the secret manually with the Vault CLI.

```
vault kv get kubernetes/dev/test-external-secret
```

**Comment by jmreicha** [comment]
Getting closer but something is still missing, the new error is promising though.

```
{"level":40,"time":1576732745807,"pid":17,"hostname":"kubernetes-external-secrets-74fbf69975-lzn4n","msg":"Failed to JSON.parse value for 'secret/dev/test-external-secret', please verify that your secret value is correctly formatted as JSON. To use plain text secret remove the 'property: password'","v":1}
```

I am able to curl the secret using the Kubernetes JWT token now, I just think my ExternalSecret definition is off.

```
curl -H "X-Vault-Token: abc123" \
   "https://vault.tld/v1/secret/dev/test-external-secret" | jq .
{
  "request_id": "311796e0-be57-c482-7677-d535c5be4d58",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 2764800,
  "data": {
    "password": "test"
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

Removing/renaming the `property` field in the ExternalSecret I can get the secret created but when I check the value populated in the Kubernetes Secret I always see `undefined`.

**Comment by wincus** [comment]
having the same issue reported by @jmreicha . I can get the secret created correctly but its value is base64 encoded value for "undefined":

```
apiVersion: v1
data:
  password: dW5kZWZpbmVk
kind: Secret
```

If I sniff traffic I can see the secret being sent correctly to the controller so I don't think is a authentication issue.

my CRD looks like:

```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-service
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: demo
  data:
  - name: password
    key: secret/creds
```

Worthy mentioning that the STATUS reports as "SUCCESS" even when the data is not correct:

```
NAME            LAST SYNC   STATUS    AGE
hello-service   8s          SUCCESS   4m29s
```
