### ISSUE TITLE
could not find key/cert in the secret error

### ISSUE THREAD

**Issue by Saggi432** [godaddy/kubernetes-external-secrets#303]
Firstly thank you so much for writing such a great integration !
 we are planning to use this in our cluster and doing a poc.  Our backend is a aws secret manager, when we try to store the tls cert and key we are facing the below error.. it seems like it cannot find the property for key and cert.. 

I created the secret in secret manager by using the below json and the same can be found in the plaintext and secret key value on aws secret manager UI.

I am not sure where i am doing wrong here.. can you guide me here with your inputs ?

Thank you for your time!

```json
{
  "tls.crt": "BEGIN_CERTIFICATE--blahblah",
  "tls.key" "BEGIN_CERTITICATE---blahblah"
}
```

```json
{"level":50,"time":1584552805300,"pid":18,"hostname":"-secret-manager-kubernetes-external-secrets-59bf8445572bkgz","msg":"failure while polling the secret default/basic-tls","stack":"Error: Could not find property key in basic-tls\n    at /app/lib/backends/kv-backend.js:45:17\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Promise.all (index 1)\n    at async Promise.all (index 1)\n    at async SecretsManagerBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:99:42)\n    at async Poller._createSecretManifest (/app/lib/poller.js:88:18)\n    at async Poller._upsertKubernetesSecret (/app/lib/poller.js:152:28)\n    at async Poller._poll (/app/lib/poller.js:115:7)","type":"Error","v":1}
```

```json
{"level":50,"time":1584552794585,"pid":18,"hostname":"secret-manager-kubernetes-external-secrets-59bf8445572bkgz","msg":"failure while polling the secret default/basic-tls","stack":"Error: Could not find property crt in basic-tls\n    at /app/lib/backends/kv-backend.js:45:17\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)\n    at async SecretsManagerBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:99:42)\n    at async Poller._createSecretManifest (/app/lib/poller.js:88:18)\n    at async Poller._upsertKubernetesSecret (/app/lib/poller.js:152:28)\n    at async Poller._poll (/app/lib/poller.js:115:7)","type":"Error","v":1}
```

Below is the yaml for the cert creation.

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: basic-tls
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  data:
    - key: basic-tls
      name: tls.crt
      property: crt
    - key: basic-tls
      name: tls.key
      property: key
```
