### ISSUE TITLE
 unable to parse tls.crt from the generated secret from ingress resource

### ISSUE THREAD

**Issue by Saggi432** [godaddy/kubernetes-external-secrets#336]
I created a secret in aws secret manager and tried to mount the secret into an ingress resource and nginx complains with the below error. 

`Error obtaining X.509 certificate: unexpected error creating SSL Cert: no valid PEM formatted block found` 

when i run through openssl the cert seems to be tampered when i stored it in aws secret manager. 

This not an issue with the k8s external secrets  but i wanted to know from the experts a best way to store the tls.crt and tls.key in aws-secret manager to avoid such errors.. i did try this awk command to append newline but that was of no use as well. I am sure you must have encountered during your tests hence this question...

**THANK YOU AGAIN!**

` awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' tls.cert`

`openssl x509 -in /tmp/tru.crt -text -noout
unable to load certificate
139641507415704:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE`

Below is the yaml for the cert creation.

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: basic-tls
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  data:
    - key: basic-tls
      name: tls.crt
      property: tls.crt
    - key: basic-tls
      name: tls.key
      property: tls.key
```
