### ISSUE TITLE
Hashicorp Vault admits dataFrom to capture every value in kv v2

### ISSUE THREAD

**Issue by arielvinas** [godaddy/kubernetes-external-secrets#346]
In the Readme is says that:

> Vault values are matched individually. If you have several keys in your Vault secret, you will need to add them all separately

But I tried using dataFrom, just like in AWS Secret Manager to capture every value in a kv secret (running kv v2) in Vault v1.3.4, and works perfectly.

I think it should be changed in the doc, since its a great feature and already supported.

Example using vault:

```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test
spec:
  backendType: vault
  vaultMountPoint: test
  vaultRole: test
  dataFrom:
    - kv/data/test/test
```
