### ISSUE TITLE
Include creation of secret of type kubernetes.io/dockerconfigjson and not just Opaque

### ISSUE THREAD

**Issue by sumanmohan** [godaddy/kubernetes-external-secrets#359]
Hi Team,
We were able to successfully create the ExternalSecret and we did see a secret being created in our kubernetes cluster which is of type "Opaque". 

We would like to understand if there is anyway the ExternalSecrets Manager can also create a secret of type "kubernetes.io/dockerconfigjson" which we can use ? This type of secret is required when we need to pull docker images for our pods from our private registry. 

Thanks!

**Comment by Flydiverny** [comment]
@sumanmohan you can override type using `template` like in this example:

https://github.com/godaddy/kubernetes-external-secrets/blob/b345ffd6d82bf268cd369368c77c54a87b664eec/examples/tls-example.yml#L7-L8

**Comment by sumanmohan** [comment]
@Flydiverny thanks a lot for your suggestion. I tried the example mentioned here https://github.com/godaddy/kubernetes-external-secrets/blob/master/examples/dockerconfig-example.yml and I was able to create an ExternalSecret of type dockerconfigjson. 

But there is an issue when we use the secret which gets created as we are unable to still use the secret to pull a image from private docker registry. For example, the conventional way to create a secret is mentioned here https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line and when we use this secret we are able to pull the image but unable to use the secret created by External Secrets manager. 

So is there any other change we need to do to our ExternalSecret manager yaml file to make the secret work? We have stored the secrets in AWS secrets manager as a key/value pair.

**Comment by Flydiverny** [comment]
Check the resulting secret and see if it yields the expected result, if not you probably need to store in another format in the backend or change the external secret to extract the value as expected.

I've used the example linked above as a demo before

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dockerconfig-example
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: /development/dockerhub
      name: .dockerconfigjson
```

Storing the secret as plain text in secrets manager

```json
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "<actual credentials>"
    }
  }
}
```
