### ISSUE TITLE
Pod doesn't assume service account

### ISSUE THREAD

**Issue by Gfeuillen** [godaddy/kubernetes-external-secrets#368]
Hi, I have set up IRSA using the AWS doc. But the `kubernetes-external-service` pod fails to assume the role set up in the service account:

Error:
```
"User: arn:aws:sts::<ACCOUNT_ID>:assumed-role/eksctl-<CLUSTER_NAME>-nodegroup-m-NodeInstanceRole-1UU8XUZSIV6RZ/i-0e5afb93460d609d2 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<ACCOUNT_ID>:role/eks-secretsmanager"
```

If I explicitly let the instance role assume `arn:aws:iam::<ACCOUNT_ID>:role/eks-secretsmanager` then it all works fine (secrets get created, etc ..). What I don't understand is that setting OpenId along with:

```
---
# Source: kubernetes-external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretsmanager-readonly
  namespace: "prod-us-east-1"
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-3.2.0
    app.kubernetes.io/instance: manual
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/eks-secretsmanager
```

Doesn't give this role directly to the pod, but rather it tries to assume it using the instance role.

Some more infos:

Ressources I used to set this on Amazon:
* https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
* https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html

Here is what I get when running `kubectl exec <kubernetes-external-service-pod> env | grep AWS`:
```
AWS_REGION=us-east-1
AWS_ROLE_ARN=arn:aws:iam::<ACCOUNT_ID>:role/eks-secretsmanager
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
``` 

Which is the expected output.

Thanks in advance !
