### ISSUE TITLE
JSON objects in GCP Secret Manager

### ISSUE THREAD

**Issue by HawkiesZA** [godaddy/kubernetes-external-secrets#369]
Is it possible to handle JSON objects via GCP manager. For instance if I store the following JSON in a GCP Secret:

```
{
  "foo": "bar"
}
```

I would like it to be handled in a similar way that the docs describe for AWS, i.e. I can make an ExternalSecret like this:

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gcp-secrets-manager-example
spec:
  backendType: gcpSecretsManager
  data:
    - key: projects/111122223333/secrets/my-secret/versions/latest
      name: foo
      property: bar
```

However, currently it seems only string secrets are supported as line 50 in [gcp-secrets-manager-backend](https://github.com/godaddy/kubernetes-external-secrets/blob/master/lib/backends/gcp-secrets-manager-backend.js) explicitly puts the secret in another object with a key:
```
const secret = { value: version[0].payload.data.toString('utf8') }
```

Which from my understanding means the property `bar` will not be found in the object in [kv-backend](https://github.com/godaddy/kubernetes-external-secrets/blob/master/lib/backends/kv-backend.js)

```
if (!(property in parsedValue))
```
will be false, as the only allowed property is `value`.

Is there something I'm missing? If not, can this feature be added, please.
