### ISSUE TITLE
AWS secrets manager json secrets

### ISSUE THREAD

**Issue by IceCodeKillah** [godaddy/kubernetes-external-secrets#385]
I would like to be able able to create a kubernetes secret in AWS Secrets Manager from the contents of a json file. This works well as a Kubernetes secret as the json content can be base64 encoded and then mounted to the container as a file.

```
kind: Secret
data:
  credentials.json: dsadasdsdsdsome-sample-base64-encoded-json-datasdasdsadas==
type: Opaque

---

volumes:
    - name: creds
              secret:
                  secretName: gcp-credentials
volumeMounts:
          - name: creds
            mountPath: /creds
```

The problem starts when using AWS Secrets Manager as I cannot upload the secret as base64 or store the json as a secret due to Secrets Manager taking the json format and then interpreting it as key value pairs. Is there any way to solve this.....

**Comment by Flydiverny** [comment]
Should be able to create the secret with the CLI.

Binary secret:
```
aws secretsmanager create-secret --name /development/json --secret-binary ewogICJ1c2VybmFtZSI6ICJoZWxsbyB3b3JsZCIKfQo=
```

or 

String:
```
aws secretsmanager create-secret --name /development/json --secret-string '{ "username": "hello world" }'
```

Pretty sure you should be able to paste this in the web console as well, even if it shows up as editable json. 

Consume something like this:

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secretsmanager-example
spec:
  backendType: secretsManager
  data:
    - key: /development/json
      name: credentials.json
```
