### ISSUE TITLE
is it possible to merge with a pre-existing secret?

### ISSUE THREAD

**Issue by bgdnlp** [godaddy/kubernetes-external-secrets#405]
Maybe this already works somehow.

After retrieving a secret from a vault is it possible to add it to the data property of a k8s secret that already exists on the cluster, instead of creating a new secret?

Use  case:
I have an application that sets up a secret on install with a few properties (ex. encryption seed). I can add passwords to said secret's data that the app can use to connect to other applications (ex. GitHub), but it will only read them from that secret. I'd prefer not to overwrite what it sets up.

**Comment by Flydiverny** [comment]
No, this is not possible. If a secret exists with the same name it will be fully overwritten. I think getting into patching business would add a lot of complexity and questions to be answered.

Possibly you could use the template feature, to do it the other way around. Eg when creating your external secret you add whatever is on the first secret to your external secret spec.

```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-service
spec:
  backendType: secretsManager
  data:
    - key: hello-service/password
      name: password
  # optional: specify a template with any additional markup you would like added to the downstream Secret resource.
  # This template will be deep merged without mutating any existing fields. For example: you cannot override metadata.name.
  template:
    data:
      username: <existing secrets>
```
