### ISSUE TITLE
AWS Service Linked Role Not Working

### ISSUE THREAD

**Issue by kferrone** [godaddy/kubernetes-external-secrets#424]
I set up the chart to use an aws service linked role and it is not working. The pod is trying to assume the role of the worker node instead of the service account. I checked the pod and the iam token from the correct role is actually mounted to the pod. 

Here is my service account
```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubernetes-external-secrets
  namespace: foo
  labels:
    app.kubernetes.io/instance: kubernetes-external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-4.0.0
  annotations:
    eks.amazonaws.com/role-arn: >-
      arn:aws:iam::123456:role/ExternalSecretRole
    meta.helm.sh/release-name: kubernetes-external-secrets
    meta.helm.sh/release-namespace: foo
```

Here is my trust relationship:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::123456:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/123456789"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.us-west-2.amazonaws.com/id/123456789:sub": "system:serviceaccount:foo:kubernetes-external-secrets"
        }
      }
    }
  ]
}
```

Since the pod is trying to use the nodes worker role instead of the role from the service account, I am also unable to use the `spec.roleArn` in the `ExternalSecret` resource. I get an error saying the nodes worker role can't assume whatever role I put there. 

So far the only way I can get this project to work is to use a secret with AWS credentials and bind it in the chart values.
e.g.
```yaml
envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: aws-credentials
    key: id
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: aws-credentials
    key: key
```

Any ideas why it does not work with the service account?

**Comment by kferrone** [comment]
Ohhhh, never mind. Didn't quite understand the values file and docs. I've never heard service linked roles called `IRSA`...
Figured it out:
```yaml
securityContext:
  runAsNonRoot: true
  # Required for use of IRSA, see https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
  fsGroup: 65534
```
