### ISSUE TITLE
secrets manager can't find the specified secret but the secret exists

### ISSUE THREAD

**Issue by MaralKay** [godaddy/kubernetes-external-secrets#428]
Hello, we are experiencing the following issue, after having completed the steps as described in the documentation.
- created a policy that allows all AWS secrets manager actions
- attached the policy to the role our kubernetes cluster nodes use
- added an identity provider in IAM for our kubernetes cluster
- attached the identity provider for the `kubernetes-external-secrets-` serviceaccount to the role our kubernetes cluster nodes use
- made sure that the `kubernetes-external-secrets-` deployment ( and pod ) use the serviceaccount
- created a secret in AWS Secrets Manager: 
```
secret name: test123
key: "key"
value: "value"
```
- created an `ExternalSecret` resource as
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test123
spec:
  backendType: secretsManager
  roleArn: ourRole
  data:
    - name: test123
      key: key
```

But the `ExternalSecret` fails with the following error which is also noted in the pod's logs:
```
NAME      LAST SYNC   STATUS                                                    AGE
test123   5s          ERROR, Secrets Manager can't find the specified secret.   32m
```

We cannot seem to understand what is going wrong in the process. 
In order to debug, we created a pod named `debug` which runs with the same `kubernetes-external-secrets-` serviceaccount and we are able to retrieve the secret from there:
```
debug-0:/# aws --region us-east-1 secretsmanager describe-secret --secret-id test123
{
    "Name": "test123",
    "VersionIdsToStages": {
        "blablabla": [
            "AWSCURRENT"
        ]
    },
    "Tags": [],
    "LastChangedDate": 1594391006.441,
    "KmsKeyId": "arnkey",
    "LastAccessedDate": 1594339200.0,
    "ARN": "thearnofthesecret"
}
```

Could you help us find the issue please? The error we get is usually returned when we try to retrieve a secret that doesn't exist, for example:
```
➭ aws secretsmanager describe-secret --secret-id test1234
An error occurred (ResourceNotFoundException) when calling the DescribeSecret operation: Secrets Manager can't find the specified secret.
```
(indeed here we are giving an invalid `--secret-id`)
So we either have some mistake in the `ExternalSecret` yaml configuration, or this could maybe be a bug?

Thank you in advance!!

**Comment by Flydiverny** [comment]
Hi!

Which version of KES are you trying? If you are using IAM roles for service accounts and then using the `roleArn` as specified in the `ExternalResource` example above it is probably not working in version <4.1.0, so I think try upgrading to that first! Specifally thinking about these two fixes:

- pass in the Web Identity token to assumeRoleWithWebIdentity (#417) (23d511f)
- use assumeRoleWithWebIdentity when using IRSA (#416) (117b926)

**Comment by Flydiverny** [comment]
Alternatively if you are not trying to actually assume a different role for the specific secret then remove `roleArn` in the `ExternalSecret`. Eg if the IAM thats associated with service account has the access to read the secrets you should not specify a `roleArn` in each `ExternalSecret`.

But if you have a setup where you have an IAM role for the service account that should assume other roles (as specified with `roleArn`) for each secret you should upgrade to 4.1.0

**Comment by MaralKay** [comment]
Hello, thank you for the response.
We upgraded to KES version 4.2.0, but we are still experiencing the same issue. We use assumeRoleWithWebIdentity with IRSA. The `serviceaccount` is used by the Deployment, and we also removed the `roleArn` now from the `ExternalSecret` since the role is associated with the `serviceaccount`.

In order to debug more, we added a second container in the kubernetes-external-secret pod, and we are able to retrieve the secret from there with the same `serviceaccount`, even though `kubernetes-external-secret` is returning the error 
```
ERROR: Secrets manager can't find the specified secret.
```
Here are the debugging results:
```
$kubectl exec -it kubernetes-external-secrets-66fb4569b6-j4chs -c debug -- /bin/bash

kubernetes-external-secrets-66fb4569b6-j4chs:/# aws secretsmanager --region=us-east-1 get-secret-value --secret-id test123
{
    "Name": "test123", 
    "VersionId": "d82b3cf3-f335-4971-a43c-f7bc1c9d4dff", 
    "SecretString": "{\"key\":\"value\"}", 
    "VersionStages": [
        "AWSCURRENT"
    ], 
    "CreatedDate": 1594390991.307, 
    "ARN": "thesecretarn"
}
```

**Comment by Flydiverny** [comment]
@MaralKay hmm, did you override the region env vars? I see you tested using `us-east-1`

By default these are set to `us-west-2` 
```yaml
  AWS_REGION: us-west-2
  AWS_DEFAULT_REGION: us-west-2
```

**Comment by MaralKay** [comment]
@Flydiverny yes we have overriden the region... This is from the env vars of the pod:
```
- name: AWS_DEFAULT_REGION
   value: us-east-1
- name: AWS_REGION
   value: us-east-1
```

**Comment by Flydiverny** [comment]
Thanks, I'm at a loss 😄 Last try in example above you have:

```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test123
spec:
  backendType: secretsManager
  roleArn: ourRole
  data:
    - name: test123
      key: key
```

in the example cli call you used `secret-id` as `test123` this should then be the `key` prop like this:
You can use a combination of `name` to specify name in generated secret, and `property` to select which field to extract.

```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test123
spec:
  backendType: secretsManager
  roleArn: ourRole
  data:
    - name: key # name in generated secret (required)
      key: test123 # secret id in backend  (required) 
      property: key # field to extract from fetched secret (optional)
```
