### ISSUE TITLE
Setting USE_HUMAN_READABLE_LOG_LEVELS has no effect

### ISSUE THREAD

**Issue by jasper-d** [godaddy/kubernetes-external-secrets#444]
**Repro:**
- Deploy godaddy/kubernetes-external-secrets:4.2.0
- Set environment variable USE_HUMAN_READABLE_LOG_LEVELS

**Expected:**
Log levels should use human readable names

**Actual:**
Log levels are still numeric

deployment.yaml:
``` 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-external-secrets
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    app.kubernetes.io/instance: kubernetes-external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-external-secrets
      app.kubernetes.io/instance: kubernetes-external-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-external-secrets
        app.kubernetes.io/instance: kubernetes-external-secrets
    spec:
      serviceAccountName: external-secrets
      containers:
        - name: kubernetes-external-secrets
          image: "godaddy/kubernetes-external-secrets:4.2.0"
          ports:
          - name: prometheus
            containerPort: 3001
          imagePullPolicy: IfNotPresent
          resources:
            {}
          env:
          - name: "AWS_REGION"
            value: "eu-central-1"
          - name: "GOOGLE_APPLICATION_CREDENTIALS"
            value: "/app/gcp-creds/gcp-creds.json"
          - name: "LOG_LEVEL"
            value: "info"
          - name: "METRICS_PORT"
            value: "3001"
          - name: "POLLER_INTERVAL_MILLISECONDS"
            value: "10000"
          - name: "VAULT_ADDR"
            value: "http://127.0.0.1:8200"
          - name: "USE_HUMAN_READABLE_LOG_LEVELS"
            value: "true"
          # Params for env vars populated from k8s secrets
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
```
