### ISSUE TITLE
Question: pod not using the role defined on the ServiceAccount (IRSA) when fetching secrets (defaults to the EC2 node's role)

### ISSUE THREAD

**Issue by Bhashit** [godaddy/kubernetes-external-secrets#452]
This is more of a question than an issue.

I am trying to integrate the kubernetes-external-secrets (KES) into EKS based kubernetes cluster. I was trying to use IRSA (IAM Roles For Service Accounts) to add authentication.

I have added the role-arn (that's attached to a policy that provides access to the secrets-manager) to the ServiceAccount for KES. I have verified that assuming this role using the following command allows the secrets to be fetched (I ran another container with AWS-CLI in it and had it attached to the same ServiceAccount I am using for KES):

```
aws sts assume-role-with-web-identity \
--role-arn $AWS_ROLE_ARN \
--role-session-name mh9test \
--web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE \
--duration-seconds 1000
```

This works correctly, and allows me to fetch secrets correctly (in that other container I ran).

However, the KES pod doesn't assume the correct role. _It assumes the role that's attached to the EC2 instance on which it is running_. Even though `AWS_ROLE_ARN` is set as an env-var.

My main question is: why am I required to put the roleArn within the ExternalSecret if I have already specified the role-arn as an annotation on the service-account (which does get added to the pod as `AWS_ROLE_ARN` env-var). Shouldn't it fallback to using the role that's specified for the ServiceAccount as a default?

It's certainly possible I'm misunderstanding things though. Also, if it turns out that what I was expecting should be the default behavior, I'd be happy to submit changes to the code.

**Comment by Bhashit** [comment]
Would things work if the KES pod was running using fargate (referring to https://github.com/godaddy/kubernetes-external-secrets/pull/416)

**Comment by Flydiverny** [comment]
Currently there are some issues with IRSA usage due to #442 but this sounds like another issue.

Your assumption that the KES pods role should be used and there shouldn't be a need to specify a `roleArn` is correct, unless one of course wants to assume another role for that specific secret.

**Comment by Bhashit** [comment]
Looking at https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/TokenFileWebIdentityCredentials.html, it seems like it could be either an AWS SDK version issue (I haven't checked the versions yet).

> it  [sdk] will also read IAM role to be assumed from AWS_ROLE_ARN environment variable

**Comment by riccardomc** [comment]
I believe that in your test you are running your pod as `root` user, while the kubernetes-external-secrets pod is running as `non-root` by [default](https://github.com/godaddy/kubernetes-external-secrets/blob/1517333314359d5754864956bd49be83b9070120/charts/kubernetes-external-secrets/values.yaml#L89). This is an important difference because in the "Pod Configuration" section of IRSA [AWS Documentation](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html) you can read:

> By default, only containers that run as root have the proper file system permissions to read the web identity token file. You can provide these permissions by having your containers run as root, or by providing the following security context for the containers in your manifest. The fsGroup ID is arbitrary, and you can choose any valid group ID.

Therefore you should try setting `securityContext.fsGroup` for your pod. The helm chart of this project already [supports this](https://github.com/godaddy/kubernetes-external-secrets/blob/1517333314359d5754864956bd49be83b9070120/charts/kubernetes-external-secrets/values.yaml#L91).

As a side note... I believe this is a rather obscure and confusing mechanism. People in AWS seem to think the same, see [this](https://github.com/aws/containers-roadmap/issues/23#issuecomment-535176333) comment.

**Comment by Bhashit** [comment]
The pod's already running with `securityContext.fsGroup` set up to `65534`

**Comment by tymokvo** [comment]
Also experiencing this with `kubernetes-external-secrets-5.1.0` when applied with `kubectl` instead of the Helm chart.

The `env` of the Pod returns the expected role arn from the specified `ServiceRole`, but using the commands from [this comment](https://github.com/godaddy/kubernetes-external-secrets/issues/452#issuecomment-664033490) in a REPL in the `external-secrets` container returns the role of the EKS node on which the Pod is running. `process.env.AWS_ROLE_ARN` also returns the IAM role of the `ServiceAccount`. The `securityGroup.fsGroup` is already set to `65534`.

**Comment by Flydiverny** [comment]
@tymokvo just to confirm, you are saying the REPL commands _does not_ return your expected role (ie the service account role)?

**Comment by tymokvo** [comment]
Yes that's correct. It returns the role of the node.

**Comment by aliusmiles** [comment]
had the same issue, fixed by adding to values:
```
securityContext:
  runAsNonRoot: true
  fsGroup: 65534
```

worth adding a note to readme perhaps to "2. IAM roles for service accounts."? comment in values.yaml is quite easy to miss especially for "still learning" k8s noobs like me :)

**Comment by ordonezf** [comment]
I'm having the same issue as @tymokvo (also installing with kubectl instead of helm instal), the service account has a role set and I can see it when I run `env | grep AWS` inside the pod, but if I run the REPL commands I get the role from the EKS node. Tried it on 4.2.0 and 5.1.0, same results.

Already tried adding the securityContext like @aliusmiles said but that didn't work.

This is part of the error KES throws
`"message":"User: arn:aws:sts::ACCOUNT-ID:assumed-role/EKS-NODE-ROLE is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:us-east-1:ACCOUNT-ID:secret:MY-SECRET"`

**Comment by Flydiverny** [comment]
Please provide more details on environment. EKS version at least :)

When running in the pod please verify if you can read the file set in the AWS env

**Comment by tymokvo** [comment]
This is our EKS cluster version:
```
GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb"
```
Could this be a problem with the node's IAM role? I also see `cannot perform sts:AssumeRoleWithWebIdentity` if I try to set a `roleArn` for the `ExternalSecret` resource.

**Comment by ordonezf** [comment]
@Flydiverny My bad!
EKS version: v1.17.6-eks-4e7f64

**Comment by Flydiverny** [comment]
> Could this be a problem with the node's IAM role? I also see `cannot perform sts:AssumeRoleWithWebIdentity` if I try to set a `roleArn` for the `ExternalSecret` resource.

For the AssumeRuleWithWebIdentity, we made a mistake with a change introduced in 4.1.0, the revert is merged but not released (I cannot cut releases, only godaddy guys can 🤷). So for that case please stick to 4.0.0 if you can for now.

> I can read it if SecurityContext: fsGroup: 65534 is enabled in the deployment, otherwise it says Permission denied.

Aight, yeah the `fsGroup` needs to be set to fix the file permissions, this should allow external-secrets to pick up the file, and then the AWS SDKs default credential chain should detect the IAM role for service account token. The EC2 node role that gets used instead is the last fallback in the credential chain.

Will make some tests on my EKS cluster.

**Comment by Flydiverny** [comment]
I get the same results as I got on Fargate https://github.com/godaddy/kubernetes-external-secrets/issues/442#issuecomment-664084389



My helm value overrides:

```yaml
env:
  AWS_REGION: eu-west-1        
  AWS_DEFAULT_REGION: eu-west-1
  DISABLE_POLLING: true        
  LOG_LEVEL: debug

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/eksctl-fargate-test-kes-iamserviceaccount-role

image:
  tag: 4.0.0

securityContext:
  fsGroup: 65534
```

Installing using helm 3 (using chart version 5.0.0):

```sh
helm install external-secrets external-secrets/kubernetes-external-secrets -f values.yaml
```

Printing AWS envs in container 

```sh
❯ k exec -it external-secrets-kubernetes-external-secrets-db59955b-gc2fj printenv | grep AWS_

AWS_DEFAULT_REGION=eu-west-1
AWS_ROLE_ARN=arn:aws:iam::111111111111:role/eksctl-fargate-test-kes-iamserviceaccount-role
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_REGION=eu-west-1
```

```
❯ kubectl version --short
Client Version: v1.18.6
Server Version: v1.16.8-eks-fd1ea7
```

```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-service-with-role
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::111111111111:role/direct-role
  data:
    - key: hello-service/password
      name: password
```

**Comment by tymokvo** [comment]
Ok, thank you for the feedback, I will try rolling back to `4.0.0` and test.

**Comment by ordonezf** [comment]
@Flydiverny A few updates from our side:
Following [this](https://docs.aws.amazon.com/eks/latest/userguide/create-service-account-iam-policy-and-role.html) tutorial all the way doesn't work, we had to stop at step 9 of **Create an IAM role** to make it work.

Now we have a role tied to our service account and it can fetch secrets without issues.
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-kubernetes-external-secrets
  namespace: default
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam:: 111111111111:role/test-eks-secrets
  labels:
    app: kubernetes-external-secrets
```

After that I tried setting a `roleArn` to an external secret so we could limit the access a bit. This role has a policy attached so that it can only read `mysecret`.
```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: external-secret-test
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::111111111111:role/eks-test-mysecret-getter
  dataFrom:
    - path/to/mysecret
```
So apparently this works on `5.1.0` :shrug:

But, I could only make it work if **the service account has a role attached to it**, it doesn't need to have any policies attached, I'm using one without and that makes the trick I guess.
