### ISSUE TITLE
how should my vault secrets be laid out?

### ISSUE THREAD

**Issue by redscaresu** [godaddy/kubernetes-external-secrets#463]
Hi there, i am a bit confused as to how my vault secrets should be laid out when integrated into external secrets.

I read #432 and #248 but think I am missing something!  

if i do the following, you can see I have my vault secret up and running

```
❯ vault read secret/example_app
Key                 Value
---                 -----
refresh_interval    768h
db_password         foobootoo
```

Next I try and create this as an external secret

```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-vault-service
spec:
  backendType: vault
  # Your authentication mount point, e.g. "kubernetes"
  vaultMountPoint: kubernetes
  # The vault role that will be used to fetch the secrets
  # This role will need to be bound to kubernetes-external-secret's ServiceAccount; see Vault's documentation:
  # https://www.vaultproject.io/docs/auth/kubernetes.html
  vaultRole: demo
  kvVersion: 2
  data:
  - name: db_password
    key: secret/example_app
    property: db_password
```

however this results in the following,

{"level":40,"time":1596643941482,"pid":19,"hostname":"platform-kubernetes-external-secrets-7f44644d84-54tnc","msg":"Failed to JSON.parse value for 'secret/example_app', please verify that your secret value is correctly formatted as JSON. To use plain text secret remove the 'property: db_password'"}

so if I follow the logs advice and drop the property, it does create the secret but I get an "undefined" when running a base64 -D against the value of db_password.

```
❯ kubectl get secrets hello-vault-service -o yaml
apiVersion: v1
data:
  db_password: dW5kZWZpbmVk
kind: Secret
metadata:
  creationTimestamp: "2020-08-05T16:12:01Z"
  name: hello-vault-service
  namespace: default
  ownerReferences:
  - apiVersion: kubernetes-client.io/v1
    controller: true
    kind: ExternalSecret
    name: hello-vault-service
    uid: 671879f3-9cff-40f2-82f6-a5d2568a936e
  resourceVersion: "39069856"
  selfLink: /api/v1/namespaces/default/secrets/hello-vault-service
  uid: 28eff53b-0b52-44dd-ba11-15a2cecbd129
type: Opaque
```

I think I am getting the externalsecret manifest wrong but cant quite see the problem there.

Thanks!
