### ISSUE TITLE
Allow Secret Key Name Static Prefix

### ISSUE THREAD

**Issue by midnightconman** [godaddy/kubernetes-external-secrets#524]
Either via annotation or flag, it would be nice to allow for a static prefix to be added to all externalSecret key names. At the moment if you have multiple kubernetes clusters with the same applications but different secrets, you need to specify "locality" information in both the namespace annotation and the externalSecrets key name. Here are some examples:

Namespace annotation:
```
kind: Namespace
metadata:
  name: prometheus
  annotations:
    externalsecrets.kubernetes-client.io/permitted-key-name: "12345678/prometheus/.*"
```

ExternalSecret:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: prometheus
spec:
  backendType: secretsManager
  dataFrom:
    - 12345678/prometheus/aws-credentials
```

It would be nice to add an annotation to the namespace that will automatically prefix the secret key name, so the above mentioned externalSecret could instead not contain any locality info:

Namespace:
```
kind: Namespace
metadata:
  name: prometheus
  annotations:
    externalsecrets.kubernetes-client.io/permitted-key-name: "12345678/prometheus/.*"
    externalsecrets.kubernetes-client.io/key-prefix: "12345678/prometheus/"
```

ExternalSecret:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: prometheus
spec:
  backendType: secretsManager
  dataFrom:
    - aws-credentials
```
