### ISSUE TITLE
Volume front end API

### ISSUE THREAD

**Issue by silasbw** [godaddy/kubernetes-external-secrets#78]
kubernetes-external-secrets currently has a single "front end" that writes backend data to `Secret` objects (and `Pod`s manipulate the `Secret` objects in the usual ways).  The goal of this issue is to define the API for a new frontend that wrties data to a `Volume`. This is part of the effort to [avoid putting Secrets in ETCD](https://github.com/godaddy/kubernetes-external-secrets/issues/46).

The Volume frontend API must allow engineers to declare how kubernetes external secrets writes external secret data to a `Volume`. One approach is to use annotations on the `Pod` to identify which volumes in `.spec.volumes` represent an `ExternalSecret`:

```yaml
kind: Pod
metadata:
  annotations:
    externalsecrets.kubernetes-client.io/volume/db-secrets: 'true'
    externalsecrets.kubernetes-client.io/volume/client-secrets: 'true'
spec:
  containers:
  - name: test
    image: busybox
    volumeMounts:
      - name: db-secrets
        mountPath: /db-secrets
      - name: client-secrets
        mountPath: /client-secrets
      - name: other-stuff
        mountPath: /stuff
  volumes:
  - name: db-secrets
    emptyDir:
      medium: "Memory"
  - name: client-secrets
    emptyDir:
      medium: "Memory"
  - name: other-stuff
    configMap:
      name: stuff-config
```

We should discuss the pros and cons of an approach like this and discuss other potential approaches.
