### ISSUE TITLE
Cross account secret retrieval

### ISSUE THREAD

**Issue by catalinpan** [godaddy/kubernetes-external-secrets#84]
Hi. I'm trying to use the kubernetes-external-secrets to access some secrets from another AWS account. The trust and secrets retrieval works as expected using the aws cli but it fails with the kubernetes-external-secrets with the error:

`{"level":50,"time":1559737055540,"pid":16,"hostname":"kubernetes-external-secrets-68cd796f7b-fjp67","msg":"failure while polling the secrets {\"message\":\"Invalid name. Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@!\",\"code\":\"ValidationException\",\"time\":\"2019-06-05T12:17:35.540Z\",\"requestId\":\"884b173f-xxxx-xxxx-xxxx-f916def6b609\",\"statusCode\":400,\"retryable\":false,\"retryDelay\":84.08545324727217}","v":1}`

My deployment file looks like below:

```
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test-secret
secretDescriptor:
  backendType: secretsManager
  data:
    - key: "arn:aws:secretsmanager:eu-west-2:111111111110:secret"
      name: "secret100"
```

The aws cli pull looks like below:

```
aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-2:111111111110:secret:jenkins100 --region eu-west-2


{
    "Name": "secret100",
    "VersionId": "3397d6e1-xxxx-xxxx-xxxx-293cd1ea6f02",
    "SecretString": "mySecurePassword",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": 1559259096.015,
    "ARN": "arn:aws:secretsmanager:eu-west-2:111111111110:secret:secret100-jNpM3x"
}
```

Can I have please some help with this, I'm doing something wrong?

Thanks

**Comment by jeffpearce** [comment]
I can take a look at this. On the surface it seems like it should work

**Comment by jeffpearce** [comment]
@catalinpan does it work if you specify the key as `arn:aws:secretsmanager:eu-west-2:111111111110:secret:secret10`?

**Comment by jeffpearce** [comment]
@catalinpan I think the arn is wrong in your yaml file - does it work if you specify the key as `arn:aws:secretsmanager:eu-west-2:111111111110:secret100`?

**Comment by catalinpan** [comment]
@jeffpearce thanks for the reply. I've just tested and you are right. The correct key should be 
`- key: "arn:aws:secretsmanager:eu-west-2:111111111110:secret:secret100"`. 
Just tested and it works as expected. Many thanks!

**Comment by zico-dev** [comment]
Apologies for reopening this. I am facing a somewhat similar issue (reference: https://github.com/godaddy/kubernetes-external-secrets):

Below is my yaml file:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test-secrets
secretDescriptor:
  backendType: secretsManager
  roleArn: arn:aws:iam::1234567890123:role/ExternalSecretRole
  data:
    - key: 'arn:aws:secretsmanager:us-east-1:1234567890123:secret:test-secrets'
      name: test-secrets
```
 

aws cli output:
```
aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:1234567890123:secret:test-secrets-j8Sdcr --region us-east-1
{
    "Name": " test-secrets ",
    "VersionId": "f2d90749-7ded-48e1-bbd9-20b3wrr0rw7b9c8",
    "SecretString": "{\"secretname\":\"secretvalue\"}",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": 1183151199.134,
    "ARN": "arn:aws:secretsmanager:us-east-1:1234567890123:secret:test-secrets-j8Sdcr"
}
```
When I attempt to check the status of the external secrets, it shows an error:
```
kubectl -n testing-example get es
NAME               LAST SYNC   STATUS                                                    AGE
test-secrets       0s          ERROR, Secrets Manager can't find the specified secret.   24h
```
Any ideas on why its showing "ERROR, Secrets Manager can't find the specified secret."?

 Thanks
